[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["cd backend && yarn install --frozen-lockfile"]

[phases.build]
cmds = ["cd backend && yarn build", "chmod +x start.sh"]

[start]
cmd = "./start.sh"
